/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibmwork;

import static ibmwork.IBMwork.sectNo;
import java.awt.Rectangle;
import javax.swing.JOptionPane;

/**
 *
 * @author Hidee
 */
public class testPage extends javax.swing.JFrame {
String[] getSectLabel = {"A","B","C","D","E","F","G"};
    /**
     * Creates new form testPage
     */
    public testPage() {
        initComponents();
        int row = 0;
        for(String quest:IBMwork.section[sectNo].getQuestions())
            qTable.setValueAt(quest, row++, 1);
        row = 0;
        for(int mark:IBMwork.section[sectNo].getMarks())
        {    
            if(mark!=0)
                qTable.setValueAt(mark, row, 2);
            else
                qTable.setValueAt("", row, 2);
            row++;
        }
        loginBack.setToolTipText(getBackTip());
        sectLabel.setText("SECTION " +getSectLabel[sectNo]);
        chapLeft.setText((7-sectNo)+" Section"+((7-sectNo==1)?"":"s")+ " left");
        if(sectNo<6){
            playButton.setText("NEXT");
            playButton.setToolTipText("Proceed to next section");
        }
        else{
            playButton.setText("SUBMIT");
            playButton.setToolTipText("Submit exercise and proceed to result");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sectLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        qTable = new javax.swing.JTable();
        chapLeft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white));

        loginBack.setBackground(new java.awt.Color(102, 102, 102));
        loginBack.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        loginBack.setForeground(new java.awt.Color(255, 255, 255));
        loginBack.setText("<<<");
        loginBack.setToolTipText("Go back");
        loginBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loginBack.setPreferredSize(new java.awt.Dimension(39, 21));
        loginBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELF PERCEPTION TEST");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setMaximumSize(new java.awt.Dimension(104, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(84, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(430, 24));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(loginBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        sectLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        sectLabel.setText("SECTION A");

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setMaximumSize(new java.awt.Dimension(32467, 32767));

        playButton.setBackground(new java.awt.Color(0, 102, 102));
        playButton.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        playButton.setForeground(new java.awt.Color(255, 255, 255));
        playButton.setText("NEXT");
        playButton.setActionCommand("login");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        qTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" 1", null, null},
                {" 2", null, null},
                {" 3", null, null},
                {" 4", null, null},
                {" 5", null, null},
                {" 6", null, null},
                {" 7 ", null, null},
                {" 8", null, null}
            },
            new String [] {
                "S/N", "QUESTION", "POINT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        qTable.setToolTipText("Distribute 10 points among sentences that well describes you ");
        qTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        qTable.setGridColor(new java.awt.Color(51, 51, 51));
        qTable.setMaximumSize(new java.awt.Dimension(2147483647, 300));
        qTable.setMinimumSize(new java.awt.Dimension(45, 176));
        qTable.setName(""); // NOI18N
        qTable.setPreferredSize(new java.awt.Dimension(578, 208));
        qTable.setRowHeight(26);
        qTable.setRowSelectionAllowed(false);
        qTable.setSelectionForeground(new java.awt.Color(153, 255, 255));
        qTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qTableFocusLost(evt);
            }
        });
        qTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                change(evt);
            }
        });
        jScrollPane1.setViewportView(qTable);
        if (qTable.getColumnModel().getColumnCount() > 0) {
            qTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            qTable.getColumnModel().getColumn(1).setPreferredWidth(820);
            qTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chapLeft.setFont(new java.awt.Font("Arial Black", 3, 9)); // NOI18N
        chapLeft.setText("chapters left");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chapLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(sectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chapLeft)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBackActionPerformed
        qTable.editCellAt(2, 2);
        qTable.editCellAt(qTable.getSelectedRow(),qTable.getSelectedColumn());
        setMark();
        if(sectNo-1>=0){
            sectNo--;
            testPage test = new testPage();
            test.setSize(this.getSize());
            test.setLocation(this.getLocation());
//            test.setMaximizedBounds(new Rectangle(800,710));
            test.setVisible(true);
            dispose();
        }else{
            instructionPage test = new instructionPage();
            test.setSize(this.getSize());
            test.setLocation(this.getLocation());
//            test.setMaximizedBounds(new Rectangle(800,710));
            test.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_loginBackActionPerformed

    public String getBackTip(){
        if(sectNo>0){
           return String.format("Go back to Section %s", getSectLabel[sectNo]);
        }else{
           return String.format("Go back to Instruction Page"); 
        }
    }
    
    
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
//        qTable.editingStopped(null);
        qTable.editCellAt(2, 2);
        qTable.editCellAt(qTable.getSelectedRow(),qTable.getSelectedColumn());
        setMark();
        if(wellFilled()){
            sectNo++;
            if(sectNo<7){
                testPage test = new testPage();
                test.setSize(this.getSize());
                test.setLocation(this.getLocation());
//                test.setMaximizedBounds(new Rectangle(800,710));
                test.setVisible(true);
                dispose();
            }else{
              if(JOptionPane.showConfirmDialog(null, "Are you sure you want to submit?", "Submit Exercise", 0)==JOptionPane.YES_OPTION){
                IBMwork.setMax();
                resultPage test = new resultPage();
                test.setSize(this.getSize());
                test.setLocation(this.getLocation());
//                test.setMaximizedBounds(new Rectangle(800,710));
                test.setVisible(true);
                dispose();
              }
              else
                  sectNo--;
              
            }
        }
        
    }//GEN-LAST:event_playButtonActionPerformed

    public boolean wellFilled(){
        int totalMarks=IBMwork.section[sectNo].getTotalMarks();
        if(totalMarks == 10){
            return true;
        }
        else{
            
            JOptionPane.showMessageDialog(null,"Total points: "+totalMarks+"\nTotal points allocated is "+(totalMarks>10?"more":"less")+" than 10","ErrorMessage",0);
            return false;
        }
    }
    
    public void setMark(){
        int value = 0;
        boolean err=false;
        
        for(int row=0;row<8;row++){
            err=false;
            try{
//                System.out.println(qTable.getValueAt(row, 2).toString());
                if(qTable.getValueAt(row, 2)==null)
                {
                    IBMwork.section[sectNo].marks[row]=0;
                }
                if(qTable.getValueAt(row, 2).toString().length()>0){
                    value=(int) qTable.getValueAt(row, 2);
                    IBMwork.section[sectNo].marks[row]=value;
//                    System.out.println(IBMwork.section[sectNo].marks[row]+"Z"+row);
                }
                else{
                   IBMwork.section[sectNo].marks[row]=0;
//                   System.out.println(IBMwork.section[sectNo].marks[row]+"W");    
                }
                
            }catch(Exception e){
                err=true;
            }
//            if(!err)
//               IBMwork.section[sectNo].marks[row]=value;   
        }
    }
    
    private void change(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_change
//        setMark();
    }//GEN-LAST:event_change

    private void qTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qTableFocusLost
//        qTable.editingStopped(evt);
    }//GEN-LAST:event_qTableFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testPage().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chapLeft;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginBack;
    private javax.swing.JButton playButton;
    private javax.swing.JTable qTable;
    private javax.swing.JLabel sectLabel;
    // End of variables declaration//GEN-END:variables
}
